#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

# Provisions the RabbitMQ broker for AI job dispatch
# (docs/rabbitmq-dispatch/spec.md §11.2/§11.3/§10.1).
#
# This script only ever talks to the separate `ieum-broker` compose project
# and, through it, the RabbitMQ container's own `rabbitmqctl`. It never
# touches the `ieum` release compose project or any app-main/app-ai
# container. It is idempotent: running it again on an already-provisioned
# broker reapplies permissions/tags and generates no new secrets.

die() { printf 'ieum provision rabbitmq: %s\n' "$1" >&2; exit 2; }

test_mode=false
if [[ "$EUID" -eq 0 ]]; then
  PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'; export PATH
  ETC_DIR='/etc/ieum'
  COMPOSE_FILE='/srv/ieum/broker/compose.yml'
  BROKER_ENV_FILE="$ETC_DIR/rabbitmq.env"
  CREDENTIALS_FILE="$ETC_DIR/rabbitmq-app-credentials.env"
  DOCKER_BIN='/usr/bin/docker'
  OPENSSL_BIN='/usr/bin/openssl'
  EXPECTED_OWNER=0
else
  [[ "${IEUM_PROVISION_RABBITMQ_TEST_MODE:-}" == 1 ]] || die 'must run as root'
  test_mode=true
  ETC_DIR=${IEUM_PROVISION_RABBITMQ_ETC_DIR:-}
  COMPOSE_FILE=${IEUM_PROVISION_RABBITMQ_COMPOSE_FILE:-}
  BROKER_ENV_FILE=${IEUM_PROVISION_RABBITMQ_BROKER_ENV_FILE:-}
  CREDENTIALS_FILE=${IEUM_PROVISION_RABBITMQ_CREDENTIALS_FILE:-}
  DOCKER_BIN=${IEUM_PROVISION_RABBITMQ_DOCKER_BIN:-/usr/bin/docker}
  OPENSSL_BIN=${IEUM_PROVISION_RABBITMQ_OPENSSL_BIN:-/usr/bin/openssl}
  EXPECTED_OWNER=${IEUM_PROVISION_RABBITMQ_EXPECTED_OWNER:-$(id -u)}
  [[ "$ETC_DIR" = /* && "$COMPOSE_FILE" = /* && "$BROKER_ENV_FILE" = /* && "$CREDENTIALS_FILE" = /* && "$DOCKER_BIN" = /* && "$OPENSSL_BIN" = /* ]] \
    || die 'test paths must be absolute'
fi

readonly PROJECT_NAME='ieum-broker'
readonly VHOST='/ieum'

[[ -x "$DOCKER_BIN" ]] || die 'docker executable is missing'
[[ -x "$OPENSSL_BIN" ]] || die 'openssl executable is missing'
[[ -f "$COMPOSE_FILE" && ! -L "$COMPOSE_FILE" ]] || die 'compose file is missing or unsafe'

mode_of() { stat -c '%a' -- "$1" 2>/dev/null || stat -f '%Lp' -- "$1"; }
owner_of() { stat -c '%u' -- "$1" 2>/dev/null || stat -f '%u' -- "$1"; }
require_private_root_file() {
  local path=$1 label=$2
  [[ -f "$path" && ! -L "$path" ]] || die "$label must be a regular non-symlink file"
  [[ "$(owner_of "$path")" == "$EXPECTED_OWNER" ]] || die "$label must be owned by root"
  [[ "$(mode_of "$path")" == 600 ]] || die "$label must have mode 0600"
}
require_private_root_file "$BROKER_ENV_FILE" 'broker env file'

compose() {
  "$DOCKER_BIN" compose --project-name "$PROJECT_NAME" --file "$COMPOSE_FILE" --env-file "$BROKER_ENV_FILE" "$@"
}
container_id() {
  compose ps -q rabbitmq
}
exec_rmq() {
  local cid
  cid=$(container_id)
  [[ -n "$cid" ]] || die 'rabbitmq container is not running'
  "$DOCKER_BIN" exec "$cid" rabbitmqctl "$@"
}
wait_healthy() {
  local cid attempt status
  cid=$(container_id)
  [[ -n "$cid" ]] || die 'rabbitmq container did not start'
  for ((attempt = 1; attempt <= 30; attempt++)); do
    status=$("$DOCKER_BIN" inspect --format '{{.State.Health.Status}}' "$cid" 2>/dev/null || printf 'unknown')
    [[ "$status" == healthy ]] && return 0
    sleep 1
  done
  die 'rabbitmq container did not become healthy'
}

generate_password() {
  "$OPENSSL_BIN" rand -hex 32
}

# add_user fails if the account already exists; fall back to resetting its
# password only in that case so re-running this script never rotates a
# password that was already handed to an app.
ensure_user() {
  local user=$1 password=$2
  if exec_rmq add_user "$user" "$password" >/dev/null 2>&1; then
    NEW_USERS+=("$user=$password")
  else
    exec_rmq change_password "$user" "$password" >/dev/null 2>&1 || true
  fi
}
ensure_permissions() {
  local user=$1 configure=$2 write=$3 read=$4
  exec_rmq set_permissions -p "$VHOST" "$user" "$configure" "$write" "$read" >/dev/null
}
# No arguments after the username clears every tag, so neither app account
# can ever hold the `management`/`administrator` tag (spec.md §10.1).
ensure_no_tags() {
  local user=$1
  exec_rmq set_user_tags "$user" >/dev/null
}

write_generated_credentials() {
  [[ "${#NEW_USERS[@]}" -gt 0 ]] || return 0
  local stage
  stage="$CREDENTIALS_FILE.$$.tmp"
  : >"$stage"
  chmod 600 "$stage"
  {
    printf '# Generated by provision-rabbitmq.sh — copy each RABBITMQ_PASSWORD value into\n'
    printf '# the matching /etc/ieum/app-main.env or /etc/ieum/app-ai.env, then delete\n'
    printf '# or re-secure this file. Never commit it.\n'
    local entry user_upper
    for entry in "${NEW_USERS[@]}"; do
      user_upper=$(printf '%s' "${entry%%=*}" | tr '[:lower:]' '[:upper:]')
      printf '%s\n' "${user_upper}_RABBITMQ_PASSWORD=${entry#*=}"
    done
  } >>"$stage"
  mv -f "$stage" "$CREDENTIALS_FILE"
  chmod 600 "$CREDENTIALS_FILE"
}

main() {
  NEW_USERS=()

  compose up -d >/dev/null
  wait_healthy

  # guest is loopback-only by RabbitMQ's own default, but loopback is real
  # inside the container, so it is removed unconditionally (spec.md §10.1).
  # Idempotent: `|| true` tolerates an already-deleted guest account.
  exec_rmq delete_user guest >/dev/null 2>&1 || true

  ensure_user ieum_main "$(generate_password)"
  ensure_permissions ieum_main '^ieum\.(ai|main)\..*$' '^ieum\.ai\.(jobs|retry|dlx)$' '^ieum\.main\..*$'
  ensure_no_tags ieum_main

  ensure_user ieum_ai "$(generate_password)"
  ensure_permissions ieum_ai '^ieum\.(ai|main)\..*$' '^ieum\.ai\.(results|retry|dlx)$' '^ieum\.ai\..*$'
  ensure_no_tags ieum_ai

  write_generated_credentials

  exec_rmq set_vm_memory_high_watermark absolute 512MB >/dev/null
  exec_rmq set_disk_free_limit absolute 5GB >/dev/null

  printf 'ieum provision rabbitmq: PASS\n'
}
main "$@"
